#!/usr/bin/env bash

set -o errexit
set -o pipefail

if [ "$1" == "-h" ] || [ "$1" == "-?" ] || [ "$1" == "--help" ]; then
    echo "$0 <dotfiles install dir>"
    echo "Existing dotfiles will be moved to <filename>.old"
    exit
fi

INSTALLDIR=$HOME
[ -n "$1" ] && INSTALLDIR="$1"

for i in .vimrc
do
	mv $INSTALLDIR/$i $INSTALLDIR/$i.old 2> /dev/null
	ln -s $PWD/$i $INSTALLDIR/$i;
done;

