#!/usr/bin/env bash

files=(
	.crontab
	.emacs
	.fonts.conf
	.gitconfig
	.gitignore_global
	.hgignore_global
	.hgrc
	.profile
	.stCommitMsg
	.vim
	.vimrc
	.zsh
	.zshrc
	.ssh/config
)

################################################################################

set -o errexit
set -o pipefail

if [ "$1" == "-h" ] || [ "$1" == "-?" ] || [ "$1" == "--help" ]; then
	echo "$0 <dotfiles install dir>"
	echo "Existing dotfiles will be moved to <filename>.old"
	exit
fi

INSTALLDIR=$HOME
[ -n "$1" ] && INSTALLDIR="$1"

dotfiles=$(dirname $(readlink -f "$0"))

for i in ${files[@]}
do
	echo "install ${i}"
	if [ -e $INSTALLDIR/$i ]; then
		if [ -L $INSTALLDIR/$i ]; then
			unlink $INSTALLDIR/$i 
		else
			mv -n $INSTALLDIR/$i $INSTALLDIR/$i.old 
		fi
	fi
	if [[ -e "${dotfiles}/${i}.osx" && "$OSTYPE" == "darwin"* ]]; then
		ln -sf "${dotfiles}/${i}.osx" $INSTALLDIR/$i;
	elif [[ -e "${dotfiles}/${i}.linux" && "$OSTYPE" == "linux-gnu" ]]; then
		ln -sf "${dotfiles}/${i}.linux" $INSTALLDIR/$i;
	else
		ln -sf ${dotfiles}/${i} $INSTALLDIR/$i;
	fi
	echo "install ${i} completed"
done;

echo "export DOTFILES=${dotfiles}" > ~/.zsh/dotfiles.zsh
chmod a+x ~/.zsh/dotfiles.zsh
