#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

FILE="/tmp/once-per-day-timestamp-$USER"

touch ${FILE}

date +%F |                                    ## Generate timestamp (could be a better date-spec)
	tee "${FILE}-tmp" |      ## Save a copy for later usage
	cmp -s - ${FILE} ||       ## Fail if date-spec changed
	{
		## In that case, update timestamp
		mv "${FILE}-tmp" ${FILE} &&

		## And only if that succeeds, run your code
		cd $DOTFILES && echo 'update dotfiles ...' && git pull --quiet
	}
